name: Rust release
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: 
          - target: i686-unknown-linux-gnu
            command: cargo 
          - target: x86_64-unknown-linux-gnu
            command: cargo
          - target: aarch64-linux-android
            command: cross
          - target: armv7-linux-androideabi
            command: cross
          - target: x86_64-linux-android
            command: cross
          - target: i686-linux-android
            command: cross


    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # related to https://github.com/actions/runner/issues/2468 
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: install build deps
        run : |
          sudo apt -y update && sudo apt -y install build-essential gcc-multilib 

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install Cross
        if: matrix.command == 'cross'
        run: |
          # wait for next version of cross related to https://github.com/cross-rs/cross/issues/1222
          cargo install --git https://github.com/cross-rs/cross cross

      - name: build
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          CARGO_PROFILE_RELEASE_STRIP: "true"
        run: ${{ matrix.command }} build --target=${{ matrix.target }} --release

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          TAR_NAME=$(printf "riche-%s.tar.gz" $(echo ${{ matrix.target }} | sed 's/-unknown//g' ) )

          tar czvf ../../../${TAR_NAME} riche
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          files: 'riche*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
